
console.log('Hi')
console.log(123)
console.log(true)
console.log({name: 'Du Thanh Duoc', age: 25})
console.table({name: 'Du Thanh Duoc', age: 25})
console.warn('Canh bao')
console.error('Loi roi')
// console.clear()
console.time('Hello')
  console.log(123)
  console.log(123)
  console.log(123)
  console.log(123)
  console.log(123)
  console.log(123)
  console.log(123)
console.timeEnd('Hello')